package com.example.flashcardstudy.data

import androidx.room.Entity
import androidx.room.ForeignKey
import androidx.room.Index
import androidx.room.PrimaryKey

/** Tracks how a flashcard was originally created. */
enum class CardSource {
    /** Typed in manually by the user. */
    MANUAL,
    /** Generated by AI from a PDF document. */
    AI_PDF,
    /** Generated by AI from an image (photo, scan). */
    AI_IMAGE,
    /** Generated by AI from a document file (DOCX, TXT, etc.). */
    AI_DOC,
    /**
     * Legacy value — cards imported from a file before source-type
     * granularity was added.  Treated as a generic "file" group in the UI.
     */
    AI_FILE,
    /** Generated by AI from a typed topic. */
    AI_TOPIC,
}

@Entity(
    tableName = "flashcards",
    foreignKeys = [
        ForeignKey(
            entity = Category::class,
            parentColumns = ["id"],
            childColumns = ["categoryId"],
            onDelete = ForeignKey.CASCADE,
        )
    ],
    indices = [Index(value = ["categoryId"])]
)
data class Flashcard(
    @PrimaryKey(autoGenerate = true) val id: Long = 0,
    val categoryId: Long,
    val question: String,
    val answer: String,
    val interval: Int,
    val easeFactor: Double,
    val repetitions: Int,
    val nextReviewDate: Long,
    /** Origin of this card — defaults to MANUAL for backward compatibility. */
    val source: CardSource = CardSource.MANUAL,
    /**
     * Human-readable label for the generation session.
     * e.g. "Photosynthesis" for AI topic, "chapter3.pdf" for a file import.
     * Null for manually added cards.
     */
    val sourceLabel: String? = null,
)